---
title: ServerTitle

headerStyle: clean

background:
  image: https://4kwallpapers.com/images/walls/thumbs_3t/23838.jpg
  blur: sm
  saturate: 50
  brightness: 50
  opacity: 80

theme: dark
color: zinc
useEqualHeights: true

quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true

hideVersion: true
hideErrors: true
statusStyle: "dot"
tlsInsecure: true

layout:
  Infrastructure:
    tab: Server Management
    header: false
    style: row
    columns: 2
  Network:
    tab: Network Management
    header: false
    style: row
    columns: 2
  Media & Storage:
    tab: Media Management
    header: false
    style: row
    columns: 2
  Calendar:
    header: false
    style: row
  Monitoring:
    header: true
    style: row
    columns: 2
  sidebar_server:
    tab: Server Management
    header: false
    style: row
  sidebar_network:
    tab: Network Management 
    header: false
    style: row
  sidebar_media:
    tab: Media Management
    header: false
    style: row
  FavSites:
    iconsOnly: true
    header: false
    style: row
    columns: 4